# TachyGIS-Konfigurationsdatei
# ============================
# Version: 0.00.1 (allererste Idee)
# Stand: 2025-03-03

AutoSave_enabled: True
AutoSave_interval_in_min: 15
AutoSave_keep_last_n_backups: 10

# Punkte Import
default_importordner: "./../Jobs"

# Punkte Export
default_exportordner: "./../Jobs"

# Profile-Tool
# ------------
# Werte, mit denen Profile in den Attributen obj_typ, obj_art und obj_spez
# gekennzeichnet sind (% ist Platzhalter f√ºr eine beliebige Zeichenfolge)

# hier als Beispiel LfA-SN
ProfileTool_ProfilPP_ObjTyp: "Passpunkt_PP"
ProfileTool_ProfilPP_ObjArt: "Profil_PP"
ProfileTool_ProfilPP_ObjSpez: "%"

Digitize_display_points: ["Passpunkt_PP", "Fund_FUN", "Probe_PRB"]
Digitize_Befund_ObjTyp: "Befund_B"
Digitize_Profil_ObjTyp: "Profil_PRF"

Transformation_colNameGcpSource: "Festpunkt_FP" 

GeoRef_Profil_ObjTyp: "Profil_PRF"
GeoRef_Profil_ColName: "prof_nr"
GeoRef_Fotoentzerrpunkt_ObjTyp: "Passpunkt_PP"
GeoRef_Fotoentzerrpunkt_ObjArt: "Profil_PP"